CNAE:
LOAD cd_cnpj as chave_fato, 
     cod_ordem, 
     cod_ramo, 
     desc_ramo, 
     chave_cnae
FROM
[..\..\files\dataMirrors\extract_cnae.csv]
(txt, codepage is 28591, embedded labels, delimiter is ';', msq);

STORE CNAE INTO '..\..\files\dataTransformed\CNAE.qvd';
STORE CNAE INTO '..\..\files\storage_pbi\CNAE.csv'(txt);


SETOR_ATIVIDADE:
LOAD ramo_atividade, 
     divisao, 
     chave_cnae
FROM
[..\..\files\dataMirrors\extract_setor_atividades.csv]
(txt, utf8, embedded labels, delimiter is ';', msq);

STORE SETOR_ATIVIDADE INTO '..\..\files\dataTransformed\SETOR_ATIVIDADE.qvd';
STORE SETOR_ATIVIDADE INTO '..\..\files\storage_pbi\SETOR_ATIVIDADE.csv'(txt);

EMPRESAS_TEMP:
LOAD cd_cnpj, 
     fl_matriz, 
     dt_abertura, 
     nm_razao_social, 
     cd_natureza_juridica, 
     de_natureza_juridica, 
     nm_logradouro, 
     nu_logradouro, 
     cd_cep, 
     nm_bairro, 
     nm_municipio, 
     sg_uf, 
     de_situacao, 
     de_classif_natureza_juridica, 
     vl_latitude, 
     vl_longitude, 
     vl_total_veiculos_antt, 
     vl_total_veiculos_leves, 
     vl_total_veiculos_pesados, 
     fl_optante_simples, 
     qt_filial, 
     fl_optante_simei, 
     de_saude_tributaria, 
     de_nivel_atividade
FROM
[..\..\files\dataMirrors\extract_empresas.csv]
(txt, codepage is 28591, embedded labels, delimiter is ';', msq);

NoConcatenate
EMPRESAS:
LOAD 
	 cd_cnpj as chave_fato,
     if(fl_matriz = 1, 'SIM', 'NÃO') AS flag_matriz, 
     dt_abertura, 
     nm_razao_social, 
     cd_natureza_juridica, 
     de_natureza_juridica, 
     nm_logradouro, 
     nu_logradouro, 
     cd_cep, 
     nm_bairro, 
     nm_municipio, 
     sg_uf, 
     de_situacao, 
     de_classif_natureza_juridica, 
     vl_latitude, 
     vl_longitude,  
     qt_filial,  
     de_saude_tributaria, 
     de_nivel_atividade,
     if(vl_total_veiculos_antt > 0, 'SIM', 'NÃO') AS registro_antt,  
     if(fl_optante_simples = 1, 'SIM', 'NÃO') AS flag_optante_simples,  
     if(fl_optante_simei = 1, 'SIM', 'NÃO') AS flag_optante_simei
Resident EMPRESAS_TEMP;

STORE EMPRESAS INTO '..\..\files\dataTransformed\EMPRESAS.qvd';
STORE EMPRESAS INTO '..\..\files\storage_pbi\EMPRESAS.csv'(txt);
 
FATO_EMPRESAS:
LOAD 
     cd_cnpj as chave_fato,
     cd_cnpj as quantidade_empresa,      
     vl_total_veiculos_antt, 
     vl_total_veiculos_leves, 
     vl_total_veiculos_pesados,
     if(vl_total_veiculos_leves+vl_total_veiculos_pesados >= 0 and vl_total_veiculos_leves+vl_total_veiculos_pesados <= 5,'0 a 5',
       if(vl_total_veiculos_leves+vl_total_veiculos_pesados >= 6 and vl_total_veiculos_leves+vl_total_veiculos_pesados <= 10,'6 a 10',
         if(vl_total_veiculos_leves+vl_total_veiculos_pesados >= 11 and vl_total_veiculos_leves+vl_total_veiculos_pesados <= 15,'11 a 15',
           if(vl_total_veiculos_leves+vl_total_veiculos_pesados >= 16 and vl_total_veiculos_leves+vl_total_veiculos_pesados <= 30,'16 a 30',
             if(vl_total_veiculos_leves+vl_total_veiculos_pesados >= 31 and vl_total_veiculos_leves+vl_total_veiculos_pesados <= 50,'31 a 50',
               if(vl_total_veiculos_leves+vl_total_veiculos_pesados > 50,'> 50','0 a 5')))))) as faixa_veiculos
Resident EMPRESAS_TEMP;

STORE FATO_EMPRESAS INTO '..\..\files\dataTransformed\FATO_EMPRESAS.qvd';
STORE FATO_EMPRESAS INTO '..\..\files\storage_pbi\FATO_EMPRESAS.csv'(txt);


DROP Table EMPRESAS_TEMP;



